version: '3'

services:
  postgres_pagar:
    container_name: postgres_pagar
    image: postgres:alpine
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin